{{- $root := . }}
{{- with .Values }}
{{- if and (eq .enabled true) (eq .servicemonitor.enabled true)}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $root.Release.Name }}
  labels:
    {{- include "geth.labels" $root | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ $root.Release.Name }}
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    any: true

{{- end }}
{{- end }}