apiVersion: v1
kind: Service
metadata:
  name: {{ include "prysm-beacon.fullname" . }}
  labels: 
    {{- include "prysm-beacon.labels" . | nindent 4 }}
    app: {{ template "prysm-beacon.name" . }}
spec:
  selector:
    {{- include "prysm-beacon.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.ports.metrics  }}
      protocol: TCP
    - name: rpc
      port: {{ .Values.ports.rpc  }}
      protocol: TCP
    - name: discovery-tcp
      port: {{ .Values.ports.discovery  }}
      protocol: TCP
    - name: discovery-udp
      port: {{ .Values.ports.discovery  }}
      protocol: UDP