enabled: true

image:
  repository: sigp/lighthouse
  tag: stable
  pullPolicy: Always

datadir: /data

container:
  command:
    - lighthouse
    - validator
  args:
    - --datadir=/data
    - --debug-level=info
    - --network=pyrmont
    - --beacon-nodes=http://lighthouse-beacon:5052
    - --graffiti="Lighthouse"

# Copy keystore files based on what's described in the auto discovery feature doc
# ref: https://lighthouse-book.sigmaprime.io/validator-management.html?highlight=--secrets-dir#populating-the-validator_definitionsyml-file
# Create these secrets with `kubectl` prior. See Readme.

keystoreSecretName: eth2-validator-keystore
passwordSecretName: eth2-validator-password

ports:
  metrics: 5064

storage:
  persistent: false
  emptyDir: false
  claim: false
  capacity: 1Gi

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 100m
  #   memory: 256Mi
  # limits:
  #   cpu: 200m
  #   memory: 512Mi

service:
  enabled: true
  type: ClusterIP

servicemonitor:
  enabled: false

affinity: {}

nodeSelector: {}

tolerations: []
